name: schuldaten_hub
description: A new Flutter project.
publish_to: 'none'
version: 0.4.11

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  camera_windows: ^0.2.2
  calendar_date_picker2: ^1.1.5
  carousel_slider: ^4.2.1
  collection: ^1.17.1
  connectivity_plus: ^6.0.3
  crop_image: ^1.0.12
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  encrypt: ^5.0.3
  extended_image: ^8.2.1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations: 
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_settings_ui: ^3.0.1
  gap: ^3.0.1
  icon_decoration: ^2.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  listenable_collections: ^1.0.0
  logger: ^2.3.0
  mobile_scanner: ^5.1.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  pdf: ^3.10.7
  qr_flutter: ^4.1.0
  top_snackbar_flutter: ^3.1.0
  watch_it: ^1.4.2
  widget_zoom: ^0.0.2
  window_manager: ^0.3.9
  image_picker_platform_interface: ^2.9.3
  camera: ^0.10.5+9
  transparent_image: ^2.0.1
  table_calendar: ^3.1.2
  provider: ^6.1.2
  url_launcher: ^6.3.0
  pasteboard: ^0.2.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.6
  build_runner: ^2.4.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
msix_config:
  display_name: Schuldaten Hub
  publisher_display_name: Medien-Sandkasten
  identity_name: de.medien-sandkasten.schuldaten-hub
  msix_version: 1.0.0.1
  logo_path: V:\schuldaten_hub_logo.png
  capabilities: internetClient
