name: schuldaten_hub
description: A new Flutter project.
publish_to: 'none'
version: 0.4.5+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  #camera_windows: ^0.2.6+1
  calendar_date_picker2: ^1.1.8
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  crop_image: ^1.0.15
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  encrypt: ^5.0.3
  eventflux: ^2.2.1
  #extended_image: ^8.3.1
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_launcher_icons: ^0.14.1
  flutter_localizations: 
    sdk: flutter
  flutter_secure_storage: ^8.1.0 # not using 9.2.2 because of https://github.com/mogol/flutter_secure_storage/issues/634
  flutter_settings_ui: ^3.0.1
  gap: ^3.0.1
  #icon_decoration: ^2.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  listenable_collections: ^1.0.0
  logger: ^2.4.0
  mobile_scanner: ^6.0.1
  package_info_plus: ^8.0.3
  path_provider: ^2.1.4
  pdf: ^3.11.1
  qr_flutter: ^4.1.0
  top_snackbar_flutter: ^3.1.0
  watch_it: ^1.6.0
  widget_zoom: ^0.0.4
  window_manager: ^0.4.2
  image_picker_platform_interface: ^2.10.0
  camera: ^0.11.0
  transparent_image: ^2.0.1
  table_calendar: ^3.1.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  pasteboard: ^0.3.0
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.5.3
  hooks_riverpod: ^2.5.4
  riverpod_annotation: ^2.5.3
  flutter_hooks: ^0.20.5
  html: ^0.15.4
  http: ^1.2.2
  flutterware: ^0.5.1
  # zxing_lib: ^1.1.2
  buffer_image: ^0.3.12
  qr_code_vision: ^0.1.2
  isbn: ^1.0.4

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^4.0.0
  #msix: ^3.16.8
  build_runner: ^2.4.6
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

dependency_overrides:
  archive: ^3.6.1
# msix_config:
#   display_name: Schuldaten Hub
#   publisher_display_name: Medien-Sandkasten
#   identity_name: de.medien-sandkiste.schuldaten-hub
#   msix_version: 1.0.0.1
#   app_installer: #<-- app installer configuration
#     publish_folder_path: V:\
#   logo_path: V:\schuldaten_hub_logo.png
#   capabilities: internetClient
