open_api_config = {
    "TITLE": "School Data Hub",
    "DESCRIPTION": "A backend tool for managing complex lists out of the pocket.",
    "DOCS_FAVICON": "https://hermannschule.de/apps/favicon-32x32.png",
    "SECURITY_SCHEMES": {
        "ApiKeyAuth": {"type": "apiKey", "in": "header", "name": "x-access-token"},
        "basicAuth": {"type": "http", "scheme": "basic"},
    },
    "TAGS": [
        {"name": "Auth", "description": "Basic Auth"},
        {"name": "User", "description": "User endpoints"},
        {"name": "File Imports", "description": "File imports"},
        {"name": "Pupil", "description": "Pupil endpoints"},
        {"name": "Schooldays", "description": "Schoolday endpoints"},
        {"name": "Missed Classes", "description": "MissedClass endpoints"},
        {"name": "Schoolday Events", "description": "Schoolday event endpoints"},
        {"name": "Competence", "description": "Competence endpoints"},
        {"name": "Competence Checks", "description": "Competence check endpoints"},
        {"name": "Competence Goals", "description": "Competence goal endpoints"},
        {
            "name": "Competence Report",
            "description": "Competence report for a school semester",
        },
        {"name": "Support Categories", "description": "Goal category endpoints"},
        {"name": "Support Level", "description": "Support Level endpoints"},
        {
            "name": "Support Category Statuses",
            "description": "Support category status endpoints",
        },
        {"name": "Support Goals", "description": "Support goal endpoints"},
        {"name": "Support Goal Checks", "description": "Support goal check endpoints"},
        {"name": "Authorizations", "description": "Authorization endpoints"},
        {
            "name": "Pupil Authorizations",
            "description": "Pupil authorization endpoints",
        },
        {"name": "School Lists", "description": "School list endpoints"},
        {"name": "Pupil Lists", "description": "Pupil list endpoints"},
        {"name": "School Semester", "description": "School semester endpoints"},
        {"name": "Workbooks", "description": "Workbook catalogue endpoints"},
        {"name": "Pupil Workbooks", "description": "Pupil workbooks endpoints"},
        {"name": "Books", "description": "Book catalogue endpoints"},
        {"name": "Pupil Books", "description": "Pupil books endpoints"},
    ],
    "CONTACT": {
        "name": "API Support",
        "url": "https://hermannschule.de/de",
        "email": "admin@hermannschule.de",
    },
    "SERVERS": [
        {"name": "Production Server", "url": "https://datahub.hermannschule.de"},
        {"name": "Test Server", "url": "https://testhub.hermannschule.de"},
        {"name": "Test Server 2", "url": "https://testhub2.hermannschule.de"},
        {"name": "Development Server", "url": "http://127.0.0.1:5000/"},
    ],
    "SWAGGER_UI_CONFIG": {
        "docExpansion": "none",
        "persistAuthorization": True,
        "filter": True,
        "tryItOutEnabled": True,
        #'operationsSorter': 'alpha',
    },
    # "TERMS_OF_SERVICE": 'http://hermannschule.de',
    "RAPIDOC_THEME": "dark",
    "RAPIDOC_CONFIG": {
        #'update-route': False,
        "persist-auth": True,
        "layout": "column",
        "render-style": "read",
        "sort-endpoints-by": "method",
        "heading-text": "School Data Hub",
        "show-method-in-nav-bar": "as-colored-block",
        "font-size": "largest",
        "bg-color": "#111",
        "nav-bg-color": "#222",
        "primary-color": "#615ba7",
        "response-area-height": "600px",
    },
}
