// ignore_for_file: constant_identifier_names

enum SearchType { pupil, room, matrixUser, list, authorization, workbook }

enum NotificationType { success, error, warning, info }

enum CompetenceFilter { E1, E2, S3, S4 }

Map<CompetenceFilter, bool> initialCompetenceFilterValues = {
  CompetenceFilter.E1: false,
  CompetenceFilter.E2: false,
  CompetenceFilter.S3: false,
  CompetenceFilter.S4: false
};

enum SchooldayEventFilter {
  sevenDays,
  admonition,
  afternoonCareAdmonition,
  admonitionAndBanned,
  parentsMeeting,
  otherEvent,
  violenceAgainstThings,
  violenceAgainstPupils,
  insultOthers,
  annoy,
  ignoreInstructions,
  disturbLesson,
  other,
  processed,
}

Map<SchooldayEventFilter, bool> initialSchooldayEventFilterValues = {
  SchooldayEventFilter.sevenDays: false,
  SchooldayEventFilter.admonition: false,
  SchooldayEventFilter.afternoonCareAdmonition: false,
  SchooldayEventFilter.admonitionAndBanned: false,
  SchooldayEventFilter.parentsMeeting: false,
  SchooldayEventFilter.otherEvent: false,
  SchooldayEventFilter.violenceAgainstThings: false,
  SchooldayEventFilter.violenceAgainstPupils: false,
  SchooldayEventFilter.insultOthers: false,
  SchooldayEventFilter.annoy: false,
  SchooldayEventFilter.ignoreInstructions: false,
  SchooldayEventFilter.disturbLesson: false,
  SchooldayEventFilter.other: false,
  SchooldayEventFilter.processed: false,
};

enum PupilSortMode {
  sortByName,
  sortByMissedExcused,
  sortByMissedUnexcused,
  sortByContacted,
  sortByLate,
  sortByCredit,
  sortByCreditEarned,
  sortByGoneHome,
  sortBySchooldayEvents,
  sortByLastSchooldayEvent,
  sortByLastNonProcessedSchooldayEvent,
}

Map<PupilSortMode, bool> initialSortModeValues = {
  PupilSortMode.sortByName: true,
  PupilSortMode.sortByMissedExcused: false,
  PupilSortMode.sortByMissedUnexcused: false,
  PupilSortMode.sortByContacted: false,
  PupilSortMode.sortByLate: false,
  PupilSortMode.sortByCredit: false,
  PupilSortMode.sortByCreditEarned: false,
  PupilSortMode.sortByGoneHome: false,
  PupilSortMode.sortBySchooldayEvents: false,
  PupilSortMode.sortByLastSchooldayEvent: false,
  PupilSortMode.sortByLastNonProcessedSchooldayEvent: false
};

enum PupilFilter {
  late,
  missed,
  home,
  unexcused,
  contacted,
  goneHome,
  present,
  notPresent,
  specialNeeds,
  ogs,
  notOgs,
  specialInfo,
  migrationSupport,
  preSchoolRevision0,
  preSchoolRevision1,
  preSchoolRevision2,
  preSchoolRevision3,
  developmentPlan1,
  developmentPlan2,
  developmentPlan3,
  fiveYears,
  communicationPupil,
  communicationTutor1,
  communicationTutor2,
  justGirls,
  justBoys,
  schoolListYesResponse,
  schoolListNoResponse,
  schoolListNullResponse,
  schoolListCommentResponse,
  authorizationYesResponse,
  authorizationNoResponse,
  authorizationNullResponse,
  authorizationCommentResponse,
  authorizationFileResponse,
  supportAreaMotorics,
  supportAreaLanguage,
  supportAreaMath,
  supportAreaGerman,
  supportAreaEmotions,
  supportAreaLearning,
}

Map<PupilFilter, bool> initialFilterValues = {
  PupilFilter.late: false,
  PupilFilter.missed: false,
  PupilFilter.home: false,
  PupilFilter.unexcused: false,
  PupilFilter.contacted: false,
  PupilFilter.goneHome: false,
  PupilFilter.present: false,
  PupilFilter.notPresent: false,
  PupilFilter.specialNeeds: false,
  PupilFilter.ogs: false,
  PupilFilter.notOgs: false,
  PupilFilter.specialInfo: false,
  PupilFilter.migrationSupport: false,
  PupilFilter.preSchoolRevision0: false,
  PupilFilter.preSchoolRevision1: false,
  PupilFilter.preSchoolRevision2: false,
  PupilFilter.preSchoolRevision3: false,
  PupilFilter.developmentPlan1: false,
  PupilFilter.developmentPlan2: false,
  PupilFilter.developmentPlan3: false,
  PupilFilter.fiveYears: false,
  PupilFilter.communicationPupil: false,
  PupilFilter.communicationTutor1: false,
  PupilFilter.communicationTutor2: false,
  PupilFilter.justBoys: false,
  PupilFilter.justGirls: false,
  PupilFilter.schoolListYesResponse: false,
  PupilFilter.schoolListNoResponse: false,
  PupilFilter.schoolListNullResponse: false,
  PupilFilter.schoolListCommentResponse: false,
  PupilFilter.authorizationYesResponse: false,
  PupilFilter.authorizationNoResponse: false,
  PupilFilter.authorizationNullResponse: false,
  PupilFilter.authorizationCommentResponse: false,
  PupilFilter.authorizationFileResponse: false,
  PupilFilter.supportAreaMotorics: false,
  PupilFilter.supportAreaLanguage: false,
  PupilFilter.supportAreaMath: false,
  PupilFilter.supportAreaGerman: false,
  PupilFilter.supportAreaEmotions: false,
  PupilFilter.supportAreaLearning: false,
};
