"""empty message

Revision ID: a030d90d1f82
Revises: 
Create Date: 2024-06-13 05:51:25.212035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a030d90d1f82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schoolday_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processed_file_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processed_file_url', sa.String(length=50), nullable=True))

    with op.batch_alter_table('pupil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_care', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pupil_authorization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('school_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorized_users', sa.String(length=100), nullable=True))
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('school_semester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_conference_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('report_conference_date', sa.Date(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutoring', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('time_units', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=50), nullable=True))

    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact')
        batch_op.drop_column('time_units')
        batch_op.drop_column('tutoring')

    with op.batch_alter_table('school_semester', schema=None) as batch_op:
        batch_op.drop_column('report_conference_date')
        batch_op.drop_column('class_conference_date')

    with op.batch_alter_table('school_list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('authorized_users')

    with op.batch_alter_table('pupil_authorization', schema=None) as batch_op:
        batch_op.drop_column('file_id')

    with op.batch_alter_table('pupil', schema=None) as batch_op:
        batch_op.drop_column('emergency_care')
        batch_op.drop_column('avatar_id')

    with op.batch_alter_table('schoolday_event', schema=None) as batch_op:
        batch_op.drop_column('processed_file_url')
        batch_op.drop_column('processed_file_id')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
