"""empty message

Revision ID: d897b79ed96a
Revises: a030d90d1f82
Create Date: 2024-06-13 05:57:40.675198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd897b79ed96a'
down_revision = 'a030d90d1f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_school_list')
    with op.batch_alter_table('school_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorized_users', sa.String(length=100), nullable=True))
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('school_semester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_conference_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('report_conference_date', sa.Date(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutoring', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('time_units', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=50), nullable=True))

    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact')
        batch_op.drop_column('time_units')
        batch_op.drop_column('tutoring')

    with op.batch_alter_table('school_semester', schema=None) as batch_op:
        batch_op.drop_column('report_conference_date')
        batch_op.drop_column('class_conference_date')

    with op.batch_alter_table('school_list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('authorized_users')

    op.create_table('_alembic_tmp_school_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('list_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('list_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('list_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=5), nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=10), nullable=False),
    sa.Column('authorized_users', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id')
    )
    # ### end Alembic commands ###
